/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/
#include <bits/stdc++.h>
using namespace std;
int main()
{
    long int a = 1;
    long int b = 1;
    long int sum = 0;
    long i = 0;
    while (i < 4000000)
    {
        if (i % 2 == 0)
            sum = sum + i;
        a = b;
        b = i;
        i = a + b;
    }

    cout << sum;
    return 0;
}
